#!/bin/bash

# DNS Resolution Fix Script
# Based on the fix_dns() function from setup-bridge-unified.sh

set -e

echo "🔧 Fixing DNS resolution issues..."

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "This script must be run as root (use sudo)"
    exit 1
fi

print_status "Fixing DNS configuration..."

# Backup current resolv.conf
cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true

# Wait for network to stabilize after bridge setup
sleep 5

# Remove any immutable flag
chattr -i /etc/resolv.conf 2>/dev/null || true

# Stop conflicting DNS services first
print_status "Stopping conflicting DNS services..."
systemctl stop systemd-resolved 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true
sleep 2

# Test current DNS with timeout
if timeout 10 nslookup google.com >/dev/null 2>&1; then
    print_status "Current DNS configuration working, preserving it"
    # Start services back up
    systemctl start systemd-resolved 2>/dev/null || true
    print_success "✅ DNS is already working properly"
    exit 0
fi

print_status "Setting reliable DNS servers..."
# Create new resolv.conf with proper permissions
cat > /etc/resolv.conf << 'EOF'
# Generated by DNS fix script - Reliable DNS servers
nameserver 8.8.8.8
nameserver 1.1.1.1
nameserver 8.8.4.4
nameserver 1.0.0.1
# Local fallback
nameserver 192.168.1.1
EOF

# Set proper permissions
chmod 644 /etc/resolv.conf

# Don't make immutable - let NetworkManager manage it
# Instead, configure NetworkManager to use these DNS servers
if command -v nmcli >/dev/null 2>&1; then
    print_status "Configuring NetworkManager DNS settings..."
    # Get the first active connection name (skip header line)
    local active_conn=$(nmcli connection show --active | grep -v "NAME" | head -1 | awk '{print $1}' | tr -d ' ')
    if [[ -n "$active_conn" && "$active_conn" != "--" ]]; then
        print_status "Found active connection: $active_conn"
        nmcli connection modify "$active_conn" ipv4.dns "8.8.8.8 1.1.1.1 8.8.4.4" ipv4.ignore-auto-dns yes 2>/dev/null || print_warning "Failed to modify NetworkManager connection"
        nmcli connection up "$active_conn" 2>/dev/null || print_warning "Failed to bring up NetworkManager connection"
    else
        print_warning "No active NetworkManager connection found - skipping NetworkManager DNS configuration"
    fi
fi

# Start DNS services one by one
print_status "Starting DNS services..."
systemctl start systemd-resolved 2>/dev/null || true
sleep 3

# Test DNS with multiple attempts
local dns_works=false
for attempt in {1..3}; do
    print_status "DNS test attempt $attempt..."
    if timeout 10 nslookup google.com >/dev/null 2>&1; then
        dns_works=true
        break
    fi
    sleep 2
done

if $dns_works; then
    print_success "✅ DNS configuration successful"
else
    print_warning "DNS resolution test failed - attempting network restart"
    systemctl restart networking 2>/dev/null || systemctl restart NetworkManager 2>/dev/null || true
    sleep 8
    
    # Test again after network restart
    if timeout 10 nslookup google.com >/dev/null 2>&1; then
        print_success "✅ DNS configuration successful after network restart"
    else
        print_warning "DNS still failing - adding essential services to hosts file"
        # Add critical services to hosts as backup
        cat >> /etc/hosts << 'EOF'
# Added by DNS fix script - DNS fallback
140.82.112.4 github.com
140.82.112.3 gist.github.com
140.82.112.2 api.github.com
151.101.1.194 registry.npmjs.org
104.21.3.145 docker.com
EOF
        
        # Test GitHub specifically
        if timeout 10 nslookup github.com >/dev/null 2>&1 || ping -c 1 140.82.112.4 >/dev/null 2>&1; then
            print_success "✅ GitHub resolution working via hosts file"
        else
            print_error "❌ DNS resolution completely failed - manual intervention required"
            echo ""
            echo "Manual steps to fix DNS:"
            echo "1. Restart DNS services: systemctl restart systemd-resolved && systemctl restart NetworkManager"
            echo "2. Reboot the system: reboot"
            echo "3. Or run the full bridge setup: sudo ./scripts/setup-bridge-unified.sh fix-dns"
            exit 1
        fi
    fi
fi

print_header "DNS VERIFICATION"

print_status "Testing DNS resolution..."

# Test multiple DNS queries
test_domains=("google.com" "github.com" "docker.com" "registry.npmjs.org")

for domain in "${test_domains[@]}"; do
    if timeout 10 nslookup "$domain" >/dev/null 2>&1; then
        print_success "✅ $domain - OK"
    else
        print_warning "⚠️ $domain - FAILED"
    fi
done

# Test internet connectivity
print_status "Testing internet connectivity..."
if ping -c 2 -W 5 8.8.8.8 >/dev/null 2>&1; then
    print_success "✅ Internet connectivity working"
else
    print_warning "⚠️ Internet connectivity issue"
fi

print_header "DNS CONFIGURATION SUMMARY"

echo ""
echo "📊 DNS Configuration:"
echo "  Primary DNS: 8.8.8.8 (Google)"
echo "  Secondary DNS: 1.1.1.1 (Cloudflare)"
echo "  Tertiary DNS: 8.8.4.4 (Google)"
echo "  Fallback DNS: 1.0.0.1 (Cloudflare)"
echo ""
echo "📁 Files modified:"
echo "  - /etc/resolv.conf (DNS servers)"
echo "  - /etc/hosts (fallback entries)"
echo "  - NetworkManager configuration (if available)"
echo ""
echo "🔧 Management commands:"
echo "  - Check DNS: nslookup google.com"
echo "  - Test connectivity: ping 8.8.8.8"
echo "  - Restart DNS: systemctl restart systemd-resolved"
echo "  - Check resolv.conf: cat /etc/resolv.conf"
echo ""
print_success "🎉 DNS resolution fix completed!"

# If still having issues, suggest using the full bridge script
if ! $dns_works; then
    echo ""
    print_warning "If DNS issues persist, try the comprehensive fix:"
    echo "  sudo ./scripts/setup-bridge-unified.sh fix-dns"
    echo "  sudo ./scripts/setup-bridge-unified.sh troubleshoot"
fi
